#!/usr/bin/env npx tsx
/**
 * Copies deployment results to frontend/.env.local
 * Run this after deploying contracts to update the frontend configuration
 *
 * Usage: npx tsx e2e/scripts/copy-deployment-env.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const DEPLOYMENT_RESULT_PATH = path.join(__dirname, '../../deployment/result.json');
const FRONTEND_ENV_PATH = path.join(__dirname, '../../frontend/.env.local');

interface DeploymentResult {
  factoryAddress: string;
  factoryCodeId: number;
  marketCodeId: number;
  oracleAddress: string;
  oracleCodeId: number;
  testMarkets: Array<{
    marketId: string;
    marketAddress: string;
    collateralDenom: string;
    debtDenom: string;
  }>;
}

function main() {
  // Check if deployment result exists
  if (!fs.existsSync(DEPLOYMENT_RESULT_PATH)) {
    console.error('Deployment result not found at:', DEPLOYMENT_RESULT_PATH);
    console.error('Please run the deployment first.');
    process.exit(1);
  }

  // Read deployment result
  const result: DeploymentResult = JSON.parse(
    fs.readFileSync(DEPLOYMENT_RESULT_PATH, 'utf-8')
  );

  console.log('Found deployment result:');
  console.log(`  Factory: ${result.factoryAddress}`);
  console.log(`  Oracle: ${result.oracleAddress}`);
  console.log(`  Markets: ${result.testMarkets.length}`);

  // Generate frontend .env.local content
  const envContent = `# Local chain configuration (auto-generated by copy-deployment-env.ts)
NEXT_PUBLIC_CHAIN_ID=stone-local-1
NEXT_PUBLIC_RPC_ENDPOINT=http://localhost:26657
NEXT_PUBLIC_REST_ENDPOINT=http://localhost:1317

# Contract addresses from deployment
NEXT_PUBLIC_FACTORY_ADDRESS=${result.factoryAddress}
NEXT_PUBLIC_ORACLE_ADDRESS=${result.oracleAddress}
`;

  // Write to frontend
  fs.writeFileSync(FRONTEND_ENV_PATH, envContent);
  console.log(`\nWrote frontend/.env.local`);
  console.log('Restart the frontend dev server to pick up the new configuration.');
}

main();
